spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/my-commerce
    username: sa
    password:
  jpa:
    # show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
    defer-datasource-initialization: true

jwt:
  secret:
    key: sdfks^diSK*(jmkajs121JKLASDJ*7!M/SAS